### ISSUE TITLE
Going back to previous sections

### ISSUE THREAD

**Issue by mhann90** [Barts-Life-Science/Support#14]
You are only allowed to go back to previous sections by clicking the previous button at the bottom of the page but it would be easier to be able to select any of the sections on the left i.e. project details or detailed project information etc so you can go directly to where you want rather than continuously pressing the previous button to get to the desired section.

**Comment by UddinRuz** [comment]
Unfortunately, this functionality is not available. I asked Henry to keep the list of sections on the left hand page to be visible but if we feel it doesn't fulfil a purpose we can ask him to remove it.

**Comment by mhann90** [comment]
[like]  HANNAN, Mariya (BARTS HEALTH N... reacted to your message:
________________________________

**Comment by PA-HenryEdwards** [comment]
We have moved to using the Progress Bar instead of the Section names
