### ISSUE TITLE
Barts Health SDE page

### ISSUE THREAD

**Issue by UddinRuz** [Barts-Life-Science/Support#15]
1. "Additional Software Services" is missing &, it should read "Additional Software & Services"
2. User should be able to add more than one line of information in the free text boxes
3. If the answer to "Will you bring additional data into the SDE" is yes there should be a free text box to add "reason for bringing additional data"
4. "Will you take data out of the SDE?" is missing from the form

**Comment by stevennewhouse** [comment]
Done.
