### ISSUE TITLE
Section E

### ISSUE THREAD

**Issue by UddinRuz** [Barts-Life-Science/Support#16]
Will you be using the BH SDE? 
- Whether you answer yes or no, it takes you to the same page - Barts Health SDE.

If the answer is yes - it should take the user to the Barts Health SDE.

If the answer is no - a new set of questions should be generated:
Not using the Barts Health SDE:
- Hosting Environment
- Data Retention
- Data Transfer

**Comment by stevennewhouse** [comment]
Fixed.
