### ISSUE TITLE
Using the AD Button on the login page

### ISSUE THREAD

**Issue by stevennewhouse** [Barts-Life-Science/Support#17]
You can use an existing AD ID to create and account and log in to the data portal using 'any' organisational AD account.

This is good as it gives a certain credibility to an identity as we know where it has come from. This ID can be used to create a DAR and submit it to the DAC.

When a DAR is approved by the DAC an Entra (AD) account will be create in our Azure tenancy to access the SDE.

When a user comes back to the data portal will they be able to login with their home AD credentials or the Precision Medicine AD? In an ideal world both - this might be possible if there is a common primary key (email address?) - that we can use a common primary key between the two AD IDs so they are interchangeable?

If not then we need a process to update the details in the Data Portal so that the our AD ID can be used (or not).

**Comment by PA-HenryEdwards** [comment]
This is linked to another ticket - email to steven about the steps on this one.
